In [1]:
import pandas as pd
import matplotlib as plt
plt.rc("font", family = "Malgun Gothic")
plt.rcParams["axes.unicode_minus"] = False
import seaborn as sns

# 건기식 복용현황

## [2022년도]

In [2]:
### 2022년도 건기식 설문조사 데이터
df_2022 = pd.read_excel("./2022년_가공식품 소비자 태도조사_가구용_Rawdata.xlsx",
                      sheet_name="String",
                      usecols="GX:VN")
df_2022

,v158,v159,v160_1,v160_2,v160_3,v160_4,v160_5,v160_6,v160_7,v160_8,...,v207,v208,v210,v211,v212,v213,v214,v215,v216,v217
0,1) 알고 있다,1) 알고 있다,4) 약간 증가,4) 약간 증가,4) 약간 증가,3) 비슷,3) 비슷,3) 비슷,3) 비슷,3) 비슷,...,NaN,NaN,3) 보통이다,3) 보통이다,3) 보통이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 약간 증가할 것이다
1,1) 알고 있다,2) 모른다,3) 비슷,0) 구입 없음,0) 구입 없음,3) 비슷,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,...,NaN,NaN,4) 만족하는 편이다,5) 매우 만족한다,4) 만족하는 편이다,4) 만족하는 편이다,5) 매우 만족한다,4) 만족하는 편이다,4) 만족하는 편이다,3) 현 수준을 유지할 것이다
2,1) 알고 있다,1) 알고 있다,3) 비슷,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,2) 약간 감소,0) 구입 없음,0) 구입 없음,...,NaN,NaN,4) 만족하는 편이다,5) 매우 만족한다,5) 매우 만족한다,3) 보통이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,3) 현 수준을 유지할 것이다
3,2) 들어본 적은 있다,2) 모른다,3) 비슷,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,...,NaN,NaN,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,3) 현 수준을 유지할 것이다
4,2) 들어본 적은 있다,1) 알고 있다,3) 비슷,3) 비슷,3) 비슷,3) 비슷,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,...,NaN,NaN,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 현 수준을 유지할 것이다
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2226,2) 들어본 적은 있다,2) 모른다,3) 비슷,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,...,NaN,NaN,4) 만족하는 편이다,3) 보통이다,5) 매우 만족한다,5) 매우 만족한다,5) 매우 만족한다,4) 만족하는 편이다,5) 매우 만족한다,3) 현 수준을 유지할 것이다
2227,1) 알고 있다,2) 모른다,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,...,NaN,NaN,4) 만족하는 편이다,5) 매우 만족한다,5) 매우 만족한다,5) 매우 만족한다,4) 만족하는 편이다,3) 보통이다,5) 매우 만족한다,3) 현 수준을 유지할 것이다
2228,2) 들어본 적은 있다,1) 알고 있다,3) 비슷,3) 비슷,3) 비슷,4) 약간 증가,3) 비슷,4) 약간 증가,3) 비슷,3) 비슷,...,NaN,NaN,4) 만족하는 편이다,3) 보통이다,4) 만족하는 편이다,4) 만족하는 편이다,4) 만족하는 편이다,3) 보통이다,4) 만족하는 편이다,3) 현 수준을 유지할 것이다
2229,1) 알고 있다,2) 모른다,3) 비슷,3) 비슷,3) 비슷,3) 비슷,3) 비슷,3) 비슷,3) 비슷,3) 비슷,...,1) 필요를 느끼지 못해서,5) 가격이 비싸서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3) 현 수준을 유지할 것이다
2230,2) 들어본 적은 있다,2) 모른다,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,0) 구입 없음,3) 비슷,0) 구입 없음,0) 구입 없음,...,NaN,NaN,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 보통이다,3) 현 수준을 유지할 것이다

### - 통합 데이터
- 최종변수 : survey_2022

In [3]:
### 본인 포함 가구원 섭취 건기식 품목 정보 가져오는 함수
def getDF(df, num):
    temp = df[[f"v1001_{num}",f"v1002_{num}",f"v1003_{num}",f"v1004_{num}_1",f"v1004_{num}_2"\
               ,f"v1004_{num}_3",f"v1004_{num}_4",f"v1004_{num}_5",f"v1004_{num}_6",f"v1004_{num}_7"\
               ,f"v1004_{num}_8",f"v1004_{num}_9",f"v1004_{num}_10"]]
    temp = temp[~temp.isna().all(axis=1)]
    temp[f"v1002_{num}"] = temp[f"v1002_{num}"].astype(int)
    temp[f"v1003_{num}"] = temp[f"v1003_{num}"].astype(int)
    temp.columns=["성별","출생년도","품목수","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산","엽록소",
                  "인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]
    return temp

### 가구원 코드
nums = [11,21,31,32,33,34,35,41,51,61,62,63,64,65,71,72,73,74,75,81,82,83,84,85]

### 모든 가구원 통합
survey_2022 = pd.DataFrame()
for num in nums:
    temp = getDF(df_2022, num)
    survey_2022 = pd.concat([survey_2022, temp])

### 연령대 컬럼 생성
survey_2022["연령대"]=((2023-survey_2022["출생년도"])//10*10).astype(str)+"~"+\
                    (((2023-survey_2022["출생년도"])//10*10)+9).astype(str)

### 성별 컬럼 '여자','남자'로 표시
# - 딕셔너리로 정의
replace_sex = {'2) 여자':'여자','1) 남자':'남자'}
survey_2022["성별"].replace(replace_sex,inplace=True)

### 출생년도, 품목수 컬럼 삭제
survey_2022.drop(["출생년도","품목수"],axis=1,inplace=True)

### 원핫 인코딩 자료로 변경
survey_2022.iloc[:, 1:-1] = survey_2022.iloc[:, 1:-1].notna().astype(int)
survey_2022["섭취품목"] = survey_2022.apply(lambda row: [col for col in survey_2022.columns if row[col] == 1], axis=1)

### 컬럼 순서변경
survey_2022 = survey_2022[["성별","연령대","섭취품목","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                           "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]

### 인덱스 초기화
survey_2022 = survey_2022.reset_index(drop=True)

############ [최종 결과] ############
survey_2022

,성별,연령대,섭취품목,비타민 및 무기질,식이섬유,아미노산 및 단백질,지방산,엽록소,인삼류,페놀류,당 및 탄수화물,발효미생물류,신규기능성식품
0,여자,50~59,"[비타민 및 무기질, 발효미생물류, 신규기능성식품]",1,0,0,0,0,0,0,0,1,1
1,여자,60~69,"[비타민 및 무기질, 지방산]",1,0,0,1,0,0,0,0,0,0
2,여자,30~39,"[비타민 및 무기질, 인삼류, 신규기능성식품]",1,0,0,0,0,1,0,0,0,1
3,여자,50~59,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0
4,여자,50~59,"[비타민 및 무기질, 식이섬유]",1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3141,여자,30~39,"[비타민 및 무기질, 발효미생물류]",1,0,0,0,0,0,0,0,1,0
3142,여자,30~39,"[발효미생물류, 신규기능성식품]",0,0,0,0,0,0,0,0,1,1
3143,여자,0~9,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0
3144,여자,0~9,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0
3145,여자,30~39,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0

### - 2022년 연령대별 성별 섭취 품목 통계
- 최종 변수 : result_survey_2022

In [4]:
############ [최종 통계] ############
result_survey_2022 = survey_2022[["성별","연령대","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                                  "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]\
                                  .groupby(["연령대","성별"]).sum()
result_survey_2022

         비타민 및 무기질 식이섬유 아미노산 및 단백질  지방산 엽록소  인삼류 페놀류 당 및 탄수화물 발효미생물류 신규기능성식품
연령대   성별
0~9   남자        10    0          0    0   0    2   0        0     23       0
      여자        12    1          0    0   0    3   0        0     22       3
10~19 남자        50    1          2    9   1   14   3        2     44      17
      여자        53    3          0    3   1    8   1        0     49      11
20~29 남자        50    2          7    9   0    8   1        0     33      14
      여자        49    3          2   11   1    8   0        3     64      29
30~39 남자        88    5         12   27   2   22   2        1     52      24
      여자       125   10          8   28   1   21   2        0    107      68
40~49 남자       157    4         13   73   6   92  10        2     80      42
      여자       187    9          7   81   3   47   5        1    131      86
50~59 남자       223    8         20  136   7  165  12       12    100      43
      여자       301   19         29  207  19  121  21       11    195     151
60~69 남자       241    9         28  177   9  234  19       24    103      38
      여자       221   13         24  175   6  137  16       22    132      76
70~79 남자        34    2          6   31   1   45   4        9     12       6
      여자        35    1          5   21   1   34   0        4     18       7
80~89 남자         1    0          1    1   0    2   0        0      2       0
      여자         2    0          0    1   0    1   0        1      1       0
90~99 남자         1    0          0    0   0    1   0        0      0       0

---

## [2021년도]

In [5]:
df_2021 = pd.read_excel("./(DATA) 2021 가공식품 소비자 태도조사v18.xlsx",
                        usecols="KT:TS")
df_2021

,D9,D9_1a_1,D9_1a_2,D9_1a_3,D9_1a_4,D9_1a_5,D9_1a_6,D9_1a_7,D9_1a_8,D9_1a_9,...,D9_3_8_et,D9_3_8_etc,D10_1,D10_2,D10_3,D10_4,D10_5,D10_6,D10_7,D11
0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,5.0,5.0,5.0,4.0,4.0,4.0,3
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,3.0,3.0,4.0,4.0,3.0,3.0,4
3,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4
4,1,1.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,3.0,4.0,4.0,4.0,4.0,4.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2188,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,3.0,4.0,4.0,3.0,4.0,4.0,3
2189,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4
2190,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,4.0,4.0,4.0,5.0,4.0,4.0,3
2191,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,2.0,4.0,3.0,4.0,4.0,5.0,4
2192,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3

### - 통합 데이터
- 최종변수 : survey_2021

In [6]:
### 본인 포함 가구원 섭취 건기식 품목 정보 가져오는 함수
def getDF(df, num):
    temp = df[[f"D9_1b_1_{num}",f"D9_1b_2_{num}",f"D9_1b_3_{num}",
               f"D9_1b_4_{num}_1",f"D9_1b_4_{num}_2",f"D9_1b_4_{num}_3",
               f"D9_1b_4_{num}_4",f"D9_1b_4_{num}_5",f"D9_1b_4_{num}_6",
               f"D9_1b_4_{num}_7",f"D9_1b_4_{num}_8",f"D9_1b_4_{num}_9",f"D9_1b_4_{num}_10"]]
    temp = temp[~temp.isna().all(axis=1)]
    temp[f"D9_1b_2_{num}"] = temp[f"D9_1b_2_{num}"].astype(int)
    temp[f"D9_1b_3_{num}"] = temp[f"D9_1b_3_{num}"].astype(int)
    temp.columns=["성별","연령","품목수","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산","엽록소",
                  "인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]
    return temp

### 가구원 코드
nums = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

### 모든 가구원 통합
survey_2021 = pd.DataFrame()
for num in nums:
    temp = getDF(df_2021, num)
    survey_2021 = pd.concat([survey_2021, temp])

### 연령대 컬럼 생성
survey_2021["연령대"]=((survey_2021["연령"])//10*10).astype(str)+"~"+\
                      (((survey_2021["연령"])//10*10)+9).astype(str)

### 성별 컬럼 '여자','남자'로 표시
# - 딕셔너리로 정의
replace_sex = {2:'여자', 1:'남자'}
survey_2021["성별"].replace(replace_sex,inplace=True)

### 연령, 품목수 컬럼 삭제
survey_2021.drop(["연령","품목수"],axis=1,inplace=True)

# ### 원핫 인코딩 자료로 변경
survey_2021.iloc[:, 1:-1] = survey_2021.iloc[:, 1:-1].notna().astype(int)
survey_2021["섭취품목"] = survey_2021.apply(lambda row: [col for col in survey_2021.columns if row[col] == 1], axis=1)

### 컬럼 순서변경
survey_2021 = survey_2021[["성별","연령대","섭취품목","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                           "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]

### 인덱스 초기화
survey_2021 = survey_2021.reset_index(drop=True)

############ [최종 결과] ############
survey_2021

,성별,연령대,섭취품목,비타민 및 무기질,식이섬유,아미노산 및 단백질,지방산,엽록소,인삼류,페놀류,당 및 탄수화물,발효미생물류,신규기능성식품
0,여자,60~69,"[인삼류, 발효미생물류]",0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,남자,20~29,"[비타민 및 무기질, 식이섬유]",1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,남자,50~59,"[비타민 및 무기질, 아미노산 및 단백질, 지방산, 인삼류, 신규기능성식품]",1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,여자,50~59,"[비타민 및 무기질, 지방산, 발효미생물류, 신규기능성식품]",1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
4,여자,50~59,"[아미노산 및 단백질, 지방산, 발효미생물류, 신규기능성식품]",0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3397,남자,20~29,"[지방산, 엽록소]",0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3398,남자,20~29,"[아미노산 및 단백질, 지방산, 페놀류]",0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3399,남자,40~49,[인삼류],0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3400,여자,10~19,"[인삼류, 당 및 탄수화물]",0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3401,여자,10~19,"[비타민 및 무기질, 발효미생물류, 신규기능성식품]",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

### - 2021년 연령대별 성별 섭취 품목 통계
- 최종 변수 : result_survey_2021

In [7]:
############ [최종 통계] ############
result_survey_2021 = survey_2021[["성별","연령대","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                                  "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]\
                                  .groupby(["연령대","성별"]).sum()
result_survey_2021

          비타민 및 무기질  식이섬유  아미노산 및 단백질    지방산   엽록소    인삼류   페놀류  당 및 탄수화물  \
연령대   성별
0~9   남자        7.0   0.0         2.0    0.0   0.0    3.0   0.0       0.0
      여자       22.0   0.0         2.0    1.0   0.0    5.0   0.0       0.0
10~19 남자       63.0   0.0        10.0    6.0   1.0   14.0   1.0       1.0
      여자       84.0   0.0         4.0    5.0   0.0    4.0   1.0       1.0
20~29 남자       69.0   3.0        15.0   18.0   3.0   10.0   3.0       2.0
      여자       93.0   8.0        14.0   21.0   1.0   11.0   4.0       0.0
30~39 남자      114.0   4.0        15.0   44.0   3.0   24.0   3.0       6.0
      여자      159.0   6.0        19.0   43.0   5.0    9.0   5.0       4.0
40~49 남자      172.0   7.0        24.0   74.0  14.0   67.0  13.0      15.0
      여자      219.0  19.0        26.0   90.0  11.0   55.0  13.0      15.0
50~59 남자      227.0  10.0        56.0  137.0  19.0  117.0  10.0      23.0
      여자      286.0  17.0        72.0  171.0  19.0   87.0  21.0      17.0
60~69 남자      208.0  11.0        51.0  136.0  14.0  143.0  14.0      23.0
      여자      217.0  10.0        45.0  146.0  15.0  108.0  11.0      21.0
70~79 남자       41.0   2.0         5.0   32.0   2.0   41.0   1.0       5.0
      여자       48.0   1.0         6.0   26.0   1.0   34.0   3.0       8.0
80~89 남자        8.0   0.0         0.0    1.0   0.0    3.0   0.0       1.0
      여자        3.0   2.0         0.0    1.0   0.0    3.0   0.0       0.0

          발효미생물류  신규기능성식품
연령대   성별
0~9   남자    21.0      0.0
      여자    37.0      2.0
10~19 남자    64.0      8.0
      여자    70.0     12.0
20~29 남자    54.0     12.0
      여자    93.0     34.0
30~39 남자    83.0     31.0
      여자   131.0     56.0
40~49 남자   120.0     36.0
      여자   160.0     89.0
50~59 남자   158.0     63.0
      여자   221.0    151.0
60~69 남자   123.0     64.0
      여자   130.0     77.0
70~79 남자    24.0     12.0
      여자    26.0     16.0
80~89 남자     4.0      2.0
      여자     5.0      0.0

---

### [2020년도]

In [8]:
df_2020 = pd.read_excel("./2020_가공식품_소비자태도조사(가구용)_DATA(최종).xlsx",
                        usecols="IO:TQ")
df_2020

,D1,D1_1,D2_1,D2_2,D2_3,D2_4,D2_5,D2_6,D2_7,D2_8,...,D10_3A2,D10_3T,D11_1,D11_2,D11_3,D11_4,D11_5,D11_6,D11_7,D12
0,1,1,3,99,99,99,99,99,4,99,...,NaN,NaN,2.0,3.0,4.0,5.0,5.0,3.0,4.0,4
1,1,1,4,99,99,99,99,99,99,99,...,NaN,NaN,3.0,4.0,4.0,4.0,5.0,4.0,4.0,4
2,1,1,3,99,99,4,99,99,99,99,...,NaN,NaN,5.0,4.0,4.0,3.0,4.0,4.0,4.0,3
3,1,1,4,99,99,99,99,99,99,99,...,NaN,NaN,4.0,4.0,3.0,3.0,4.0,3.0,4.0,4
4,1,1,3,99,99,99,99,1,99,99,...,NaN,NaN,4.0,5.0,3.0,4.0,5.0,4.0,4.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1,1,2,4,2,2,2,2,3,2,...,NaN,NaN,3.0,2.0,3.0,3.0,4.0,3.0,3.0,3
1998,1,1,3,3,4,3,3,4,99,99,...,NaN,NaN,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3
1999,1,1,4,3,99,3,3,2,2,2,...,NaN,NaN,3.0,3.0,3.0,3.0,4.0,4.0,4.0,3
2000,1,1,3,2,3,3,99,3,99,1,...,NaN,NaN,3.0,3.0,3.0,3.0,3.0,4.0,3.0,3
2001,1,2,99,99,99,2,99,2,99,99,...,NaN,NaN,3.0,4.0,3.0,4.0,4.0,3.0,3.0,2

### - 통합 데이터
- 최종변수 : survey_2020

In [9]:
### 본인 포함 가구원 섭취 건기식 품목 정보 가져오는 함수
def getDF(df, num, alpha):
    temp = df[[f"D10_2_{num}",f"D10_3_{num}",f"D10_4_{num}",
               f"D10{alpha}1",f"D10{alpha}2",f"D10{alpha}3",f"D10{alpha}4",
               f"D10{alpha}5",f"D10{alpha}6",f"D10{alpha}7",f"D10{alpha}8",
               f"D10{alpha}9",f"D10{alpha}10"]]
    temp = temp[~temp.isna().all(axis=1)]
    temp[f"D10_3_{num}"] = temp[f"D10_3_{num}"].astype(int)
    temp[f"D10_4_{num}"] = temp[f"D10_4_{num}"].astype(int)
    temp.columns=["성별","연령","품목수","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산","엽록소",
                  "인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]
    return temp

### 가구원 코드
nums = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
### 건기식 코드
alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O']

### 모든 가구원 통합
survey_2020 = pd.DataFrame()
for num, alpha in zip(nums, alphabet):
    temp = getDF(df_2020, num, alpha)
    survey_2020 = pd.concat([survey_2020, temp])

### 연령대 컬럼 생성
survey_2020["연령대"]=((survey_2020["연령"])//10*10).astype(str)+"~"+\
                    (((survey_2020["연령"])//10*10)+9).astype(str)

### 성별 컬럼 '여자','남자'로 표시
# - 딕셔너리로 정의
replace_sex = {2:'여자', 1:'남자'}
survey_2020["성별"].replace(replace_sex,inplace=True)

### birth, cnt 컬럼 삭제
survey_2020.drop(["연령","품목수"],axis=1,inplace=True)

### 원핫 인코딩 자료로 변경
survey_2020.iloc[:, 1:-1] = survey_2020.iloc[:, 1:-1].notna().astype(int)
survey_2020["섭취품목"] = survey_2020.apply(lambda row: [col for col in survey_2020.columns if row[col] == 1], axis=1)

### 컬럼 순서변경
survey_2020 = survey_2020[["성별","연령대","섭취품목","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                           "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]

### 인덱스 초기화
survey_2020 = survey_2020.reset_index(drop=True)

############ [최종 결과] ############
survey_2020

,성별,연령대,섭취품목,비타민 및 무기질,식이섬유,아미노산 및 단백질,지방산,엽록소,인삼류,페놀류,당 및 탄수화물,발효미생물류,신규기능성식품
0,여자,30~39,"[비타민 및 무기질, 페놀류]",1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,여자,30~39,"[비타민 및 무기질, 발효미생물류]",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,여자,30~39,"[비타민 및 무기질, 지방산]",1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,여자,30~39,"[비타민 및 무기질, 발효미생물류]",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,남자,30~39,[비타민 및 무기질],1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3007,남자,30~39,"[인삼류, 발효미생물류]",0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3008,여자,20~29,"[비타민 및 무기질, 발효미생물류]",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3009,여자,20~29,[발효미생물류],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3010,남자,30~39,[비타민 및 무기질],1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3011,여자,30~39,[비타민 및 무기질],1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### - 2020년 연령대별 성별 섭취 품목 통계
- 최종 변수 : result_survey_2020

In [10]:
############ [최종 통계] ############
result_survey_2020 = survey_2020[["성별","연령대","비타민 및 무기질","식이섬유","아미노산 및 단백질","지방산",
                                  "엽록소","인삼류","페놀류","당 및 탄수화물","발효미생물류","신규기능성식품"]]\
                                  .groupby(["연령대","성별"]).sum()
result_survey_2020

          비타민 및 무기질  식이섬유  아미노산 및 단백질    지방산   엽록소    인삼류  페놀류  당 및 탄수화물  \
연령대   성별
0~9   남자       21.0   0.0         2.0    0.0   0.0    4.0  0.0       1.0
      여자       21.0   0.0         2.0    2.0   0.0    1.0  0.0       0.0
10~19 남자       81.0   5.0        11.0    9.0   3.0    9.0  0.0       0.0
      여자       50.0   2.0         9.0   11.0   2.0   12.0  0.0       0.0
20~29 남자       83.0   3.0         5.0   14.0   0.0   21.0  3.0       2.0
      여자      103.0   9.0         7.0   19.0   1.0   12.0  2.0       2.0
30~39 남자      129.0  11.0        12.0   33.0   4.0   49.0  4.0       1.0
      여자      189.0  25.0        19.0   37.0   6.0   20.0  8.0       4.0
40~49 남자      157.0  16.0        19.0   78.0   5.0  104.0  4.0       7.0
      여자      253.0  20.0        23.0   98.0   9.0   76.0  7.0      14.0
50~59 남자      170.0  11.0        18.0  116.0  10.0  145.0  6.0      11.0
      여자      257.0  16.0        28.0  157.0  12.0  111.0  7.0      16.0
60~69 남자      104.0   1.0        10.0   82.0   5.0  104.0  2.0       9.0
      여자      155.0   5.0        17.0  124.0   2.0  109.0  7.0      17.0
70~79 남자       32.0   0.0         5.0   24.0   0.0   52.0  0.0       6.0
      여자       50.0   1.0        12.0   42.0   2.0   44.0  1.0       5.0
80~89 여자        1.0   0.0         0.0    0.0   0.0    0.0  0.0       1.0

          발효미생물류  신규기능성식품
연령대   성별
0~9   남자    25.0      2.0
      여자    20.0      3.0
10~19 남자    61.0      3.0
      여자    44.0      3.0
20~29 남자    55.0      0.0
      여자    95.0      0.0
30~39 남자    72.0      2.0
      여자   135.0      1.0
40~49 남자    79.0      2.0
      여자   153.0      4.0
50~59 남자   100.0      3.0
      여자   159.0      7.0
60~69 남자    45.0      2.0
      여자    75.0      4.0
70~79 남자    24.0      1.0
      여자    32.0      1.0
80~89 여자     1.0      0.0

---

# [2022-2020] 3개년 연령별, 성별 섭취 현황

In [11]:
survey_total = pd.concat([survey_2022,survey_2021,survey_2020]).reset_index(drop=True)
survey_total.iloc[:, 3:] = survey_total.iloc[:, 3:].astype(int)
survey_total

,성별,연령대,섭취품목,비타민 및 무기질,식이섬유,아미노산 및 단백질,지방산,엽록소,인삼류,페놀류,당 및 탄수화물,발효미생물류,신규기능성식품
0,여자,50~59,"[비타민 및 무기질, 발효미생물류, 신규기능성식품]",1,0,0,0,0,0,0,0,1,1
1,여자,60~69,"[비타민 및 무기질, 지방산]",1,0,0,1,0,0,0,0,0,0
2,여자,30~39,"[비타민 및 무기질, 인삼류, 신규기능성식품]",1,0,0,0,0,1,0,0,0,1
3,여자,50~59,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0
4,여자,50~59,"[비타민 및 무기질, 식이섬유]",1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9555,남자,30~39,"[인삼류, 발효미생물류]",0,0,0,0,0,1,0,0,1,0
9556,여자,20~29,"[비타민 및 무기질, 발효미생물류]",1,0,0,0,0,0,0,0,1,0
9557,여자,20~29,[발효미생물류],0,0,0,0,0,0,0,0,1,0
9558,남자,30~39,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0
9559,여자,30~39,[비타민 및 무기질],1,0,0,0,0,0,0,0,0,0

In [126]:
survey_total.to_csv("./survey_total.csv", index=False)

In [16]:
total_temp = survey_total[["성별","연령대","섭취품목"]].groupby(["연령대","성별"]).count()
total_temp

          섭취품목
연령대   성별
0~9   남자    98
      여자   111
10~19 남자   317
      여자   302
20~29 남자   321
      여자   425
30~39 남자   502
      여자   697
40~49 남자   776
      여자   974
50~59 남자  1067
      여자  1390
60~69 남자   997
      여자  1035
70~79 남자   258
      여자   265
80~89 남자    13
      여자    11
90~99 남자     1